### ISSUE TITLE
Crashing today

### ISSUE THREAD

**Issue by Sage0101** [d07RiV/blizzget#2]
Worked yesterday but is crashing today. d3t

**Comment by d07RiV** [comment]
They changed the CDN config to no longer list all available builds. This is probably why other games were crashing previously, d3t just didn't get a new config until today.

Basically this means that you will not be able to find any builds other than the current one, so I'm not entirely sure if there's any point in this tool now :(

**Comment by Sage0101** [comment]
so does this mean we can no longer datamine before hand?

**Comment by d07RiV** [comment]
Yes, for reference, this is a copy of the previous CDN config for D3:  
http://pastebin.com/raw/Rf1e5K0h  
The current one is here:  
http://blzddist1-a.akamaihd.net/tpr/d3/config/07/d5/07d527cb36304d51fd1c6ef689cbca34

As you can see, it has a lot less archives (meaning they probably deleted a lot of the old files) and is missing the `builds` line, which contains hashes for every available build. Unless you can somehow find the hash for the new build beforehand, there isn't much that can be done.

I can fix it to retrieve the current build, but I'm not sure how helpful that would be, since the launcher already does the same.

**Comment by Sage0101** [comment]
Will you please fix snoparser to just get the latest build I only use it to extract the GameBalanceId.txt. Idc if everything else doesnt parse right but before the cdn change it would at least get the GameBalanceId data and then error which was totally fine with me.

**Comment by d07RiV** [comment]
Ah I see, you mean the tool at http://www.rivsoft.net/projects/other/snoparser/ ?

I just updated it, you can redownload it now.
